name: check-rust

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show Rust and Cargo version
        run: |
          rustc --version
          cargo --version
